# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Game_Done.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DoneWindow(object):
    def setupUi(self, DoneWindow):
        DoneWindow.setObjectName("DoneWindow")
        DoneWindow.resize(767, 474)
        self.centralwidget = QtWidgets.QWidget(DoneWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.done_label = QtWidgets.QLabel(self.centralwidget)
        self.done_label.setGeometry(QtCore.QRect(79, 80, 600, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setUnderline(True)
        self.done_label.setFont(font)
        self.done_label.setAlignment(QtCore.Qt.AlignCenter)
        self.done_label.setObjectName("done_label")
        self.wpm_total_label = QtWidgets.QLabel(self.centralwidget)
        self.wpm_total_label.setGeometry(QtCore.QRect(80, 186, 600, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.wpm_total_label.setFont(font)
        self.wpm_total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wpm_total_label.setObjectName("wpm_total_label")
        self.accuracy_total_label = QtWidgets.QLabel(self.centralwidget)
        self.accuracy_total_label.setGeometry(QtCore.QRect(80, 270, 600, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.accuracy_total_label.setFont(font)
        self.accuracy_total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.accuracy_total_label.setObjectName("accuracy_total_label")
        DoneWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DoneWindow)
        self.statusbar.setObjectName("statusbar")
        DoneWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DoneWindow)
        QtCore.QMetaObject.connectSlotsByName(DoneWindow)

    def retranslateUi(self, DoneWindow):
        _translate = QtCore.QCoreApplication.translate
        DoneWindow.setWindowTitle(_translate("DoneWindow", "MainWindow"))
        self.done_label.setText(_translate("DoneWindow", "All done!"))
        self.wpm_total_label.setText(_translate("DoneWindow", "TextLabel"))
        self.accuracy_total_label.setText(_translate("DoneWindow", "TextLabel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DoneWindow = QtWidgets.QMainWindow()
    ui = Ui_DoneWindow()
    ui.setupUi(DoneWindow)
    DoneWindow.show()
    sys.exit(app.exec_())
